<?php /** @var Menu $this */

use Snowdog\Academy\Component\Menu; ?>

<header>
    <nav>
        <a id="logo" href="/">
            <div>
                <span id="title">Crypto Trading Platform</span>
                <i class="fa fa-money-check-alt"></i>
                <span id="slogan">Explore the world of cryptocurrencies</span>
            </div>
        </a>
        <div id="menu">
            <ul>
                <?php foreach ($this->getMenus() as $menu): ?>
                    <?php $this->renderItem($menu) ?>
                <?php endforeach ?>
            </ul>
        </div>
    </nav>
</header>