<?php

// use Snowdog\Academy\Controller\Account;

require_once(__DIR__ . '/../common/header.phtml'); ?>

<div class="container">
    <div>
        <h1>Add Funds for: <?= $this->getUser()->getLogin(); ?></h1>

        <form action="/account/addFunds" method="post">
            <input type="number" name="fundsValue" value="0" min="0">
            <input type="submit" name="submit" value="add funds">
        </form>

    </div>
</div>

<?php require_once(__DIR__ . '/../common/footer.phtml'); ?>
